services:

  web:
    build:
      context: web
    environment:
      #CREATE_CERT: yes # Uncomment in production
      EMAIL: mhanberry1@gmail.com
      DOMAINS: quizquarterly.org,www.quizquarterly.org,api.quizquarterly.org
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt
      - quizzes:/usr/share/nginx/html/quizzes

  api:
    build:
      context: api
    environment:
      JWT_SECRET_KEY: test # Override in production
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
      - data:/app/data
      - quizzes:/app/quizzes

volumes:
  certs:
  data:
  quizzes:
