services:

  web:
    build:
      context: .
    environment:
      #CREATE_CERT: yes
      EMAIL: mhanberry1@gmail.com
      DOMAINS: quizquarterly.org,www.quizquarterly.org,api.quizquarterly.org
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt

  api:
    build:
      context: .
      dockerfile_inline: |
        from node
        workdir app
        npm init
        npm install express
    ports:
      - 8080:8080
    volumes:
      - ./api:/
      - ./web:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt

volumes:
  certs:
