services:

  web:
    build:
      context: web
    environment:
      #CREATE_CERT: yes
      EMAIL: mhanberry1@gmail.com
      DOMAINS: quizquarterly.org,www.quizquarterly.org,api.quizquarterly.org
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt

  api:
    build:
      context: api
    ports:
      - 8080:8080
    volumes:
      - ./api:/app

volumes:
  certs:
